### ISSUE TITLE
ADD OCN 41

### ISSUE THREAD

**Issue by sushiogoto** [sushiogoto/token-whitepapers#13]
#### Proposed change
Add new whitepaper url
1. Token: OCN, Odysey
2. Whitepaper url: http://www.ocnex.net/pdf/whitepaper.pdf?v=2018051802

Voting ends at: Tue Dec 11 2018 18:15:57 GMT+0000 (UTC)
Whitepapers list: https://docs.google.com/spreadsheets/d/10loB0jrEGjiftUuCzLPqALG9TjvZwsTb8eH5Q2eNmmQ/edit?usp=sharing

**Comment by sushiogoto** [comment]
This works, but also found: http://home.ocnex.net/ODYSSEY_WHITEPAPER.pdf

**Comment by rickyyean** [comment]
Voting down because spelling of token name is incorrect

**Comment by sushiogoto** [comment]
Oh whoops, just noticed. Changing my vote

**Comment by rickyyean** [comment]
Should incorrect spelling warrant a NO vote or should this be accepted if it's an honest typo?
