### ISSUE TITLE
ADD APPC 44

### ISSUE THREAD

**Issue by sushiogoto** [sushiogoto/token-whitepapers#14]
#### Proposed change
Add new whitepaper url
1. Token: APPC, AppCoins
2. Whitepaper url: https://appcoins.io/assets/images/white-paper.pdf

Voting ends at: Tue Dec 11 2018 18:21:33 GMT+0000 (UTC)
Whitepapers list: https://docs.google.com/spreadsheets/d/10loB0jrEGjiftUuCzLPqALG9TjvZwsTb8eH5Q2eNmmQ/edit?usp=sharing

**Comment by sushiogoto** [comment]
Voting down because token already exists

**Comment by sushiogoto** [comment]
This should be an 'update' instead of an 'add'

**Comment by rickyyean** [comment]
Good catch ;-)

How did you catch it?

**Comment by sushiogoto** [comment]
I did a lookup for APPC in `whitepapers.csv`. Would probably be useful to show if there's a match on the Token symbol (not name) in `whitepapers.csv`, since we use that as the 'key'
