### ISSUE TITLE
UPDATE BTX 45

### ISSUE THREAD

**Issue by sushiogoto** [sushiogoto/token-whitepapers#15]
#### Proposed change
Update whitepaper url
1. Token: BTX, Bitcoin X
2. New whitepaper url: https://bitx.tk/pdf/whitepaper.pdf
3. Reason for change: Preference for whitepaper URL that is on the official project website or social media
4. Proof: does not exist

#### Current entry
1. Token: BTX, Bitcore
2. Whitepaper url: https://github.com/dgcarlosleon/Bitcore_White_Paper_ESP_09_2018/releases/download/Bitcore/Bitcore_Whitepaper_09_2018.pdf

Voting ends on: Tue Dec 11 2018 18:21:33 GMT+0000 (UTC)
Complete list of current whitepapers: https://docs.google.com/spreadsheets/d/10loB0jrEGjiftUuCzLPqALG9TjvZwsTb8eH5Q2eNmmQ/edit?usp=sharing

**Comment by sushiogoto** [comment]
I'm downvoting this because BitcoinX's symbol is BCX (though there is some confusion as CMC lists BitcoinX as BTX too)

**Comment by rickyyean** [comment]
Wait, but BTX (Bitcoin X) has a higher market cap on CMC compare to BCX (BitcoinX). Why was this downvoted. I am protesting.
