### ISSUE TITLE
ADD BCH 47

### ISSUE THREAD

**Issue by sushiogoto** [sushiogoto/token-whitepapers#17]
#### Proposed change
Add new whitepaper url
1. Token: BCH, Bitcoin Cash
2. Whitepaper url: https://www.bitcoincash.org/bitcoin.pdf

Voting ends at: Tue Dec 11 2018 18:27:12 GMT+0000 (UTC)
Whitepapers list: https://docs.google.com/spreadsheets/d/10loB0jrEGjiftUuCzLPqALG9TjvZwsTb8eH5Q2eNmmQ/edit?usp=sharing

**Comment by yyw** [comment]
This is the bitcoin whitepaper. Even though it's the same as the bitcoin cash paper, it's not technically the same.

**Comment by rickyyean** [comment]
@yyw this is posted prominently on the bitcoincash website and linked to as their whitepaper

![screen shot 2018-12-11 at 9 59 34 am](https://user-images.githubusercontent.com/1755748/49819952-7dc0ab80-fd2b-11e8-9952-b512af3e7a8c.png)

**Comment by yyw** [comment]
I'll change my vote. This is sufficient proof.
