### ISSUE TITLE
UPDATE WIZ 49

### ISSUE THREAD

**Issue by sushiogoto** [sushiogoto/token-whitepapers#18]
#### Proposed change
Update whitepaper url
1. Token: WIZ, CrowdWiz
2. New whitepaper url: https://crowdwiz.io/docs/whitepaper-en-1507561917.pdf
3. Reason for change: Preference for whitepaper URL that is on the official project website or social media
4. Proof: Current whitepaper not hosted on project website

#### Current entry
1. Token: WIZ, CrowdWiz
2. Whitepaper url: https://www.cryptoground.com/storage/files/1529323775-crowdwiz.pdf

Voting ends on: Tue Dec 11 2018 18:41:35 GMT+0000 (UTC)
Complete list of current whitepapers: https://docs.google.com/spreadsheets/d/10loB0jrEGjiftUuCzLPqALG9TjvZwsTb8eH5Q2eNmmQ/edit?usp=sharing

**Comment by yyw** [comment]
The new link doesn't load for me...

**Comment by sushiogoto** [comment]
Same, link doesn't load for me
