### ISSUE TITLE
UPDATE DTB 50

### ISSUE THREAD

**Issue by sushiogoto** [sushiogoto/token-whitepapers#19]
#### Proposed change
Update whitepaper url
1. Token: DTB, Databits
2. New whitepaper url: https://www.augmentorsgame.com/wp-content/uploads/2018/06/25052018-DatabitsWhitepaper-v2.1.2.pdf
3. Reason for change: Preference for the latest version of the whitepaper
4. Proof: fjaipfaf

#### Current entry
1. Token: DTB, Databits
2. Whitepaper url: https://www.augmentorsgame.com/wp-content/uploads/2017/11/22112017-DatabitsWhitepaper-v2.0-.pdf

Voting ends on: Tue Dec 11 2018 18:41:37 GMT+0000 (UTC)
Complete list of current whitepapers: https://docs.google.com/spreadsheets/d/10loB0jrEGjiftUuCzLPqALG9TjvZwsTb8eH5Q2eNmmQ/edit?usp=sharing

**Comment by yyw** [comment]
I don't understand the proof

**Comment by sushiogoto** [comment]
Also don't understand the proof, but the new whitepaper appears to be newer
