### ISSUE TITLE
ADD USDC 51

### ISSUE THREAD

**Issue by sushiogoto** [sushiogoto/token-whitepapers#21]
#### Proposed change
Add new whitepaper url
1. Token: USDC, USD Coin
2. Whitepaper url: https://www.centre.io/pdfs/centre-whitepaper.pdf

Voting ends at: Tue Dec 11 2018 18:46:26 GMT+0000 (UTC)
Whitepapers list: https://docs.google.com/spreadsheets/d/10loB0jrEGjiftUuCzLPqALG9TjvZwsTb8eH5Q2eNmmQ/edit?usp=sharing

**Comment by rickyyean** [comment]
If the name of the token is wrong, should it be an "update" instead of creating two separate votes to remove then add?

**Comment by sushiogoto** [comment]
It could be a separate "Update Token Name", in which case I'll also modify "Update" to "Update Token Whitepaper"
